// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ShiftFlow.Infrastructure.Persistence;

#nullable disable

namespace ShiftFlow.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260911222815_AddAttendanceSessions")]
    partial class AddAttendanceSessions
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ShiftFlow.Domain.Entities.AttendanceSession", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CallAgentId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("EndedAtUtc")
                        .HasColumnType("datetime2(0)");

                    b.Property<DateTime>("LastSeenUtc")
                        .HasColumnType("datetime2(0)");

                    b.Property<int>("ShiftId")
                        .HasColumnType("int");

                    b.Property<DateTime>("StartedAtUtc")
                        .HasColumnType("datetime2(0)");

                    b.HasKey("Id");

                    b.HasIndex("ShiftId");

                    b.HasIndex("CallAgentId", "ShiftId")
                        .HasDatabaseName("IX_AttendanceSessions_Open")
                        .HasFilter("[EndedAtUtc] IS NULL");

                    b.HasIndex("CallAgentId", "StartedAtUtc")
                        .HasDatabaseName("IX_AttendanceSessions_CallAgent_StartedAtUtc");

                    b.ToTable("AttendanceSessions", (string)null);
                });

            modelBuilder.Entity("ShiftFlow.Domain.Entities.Availability", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CallAgentId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2(0)");

                    b.Property<DateTime>("EndUtc")
                        .HasColumnType("datetime2(0)");

                    b.Property<DateTime>("StartUtc")
                        .HasColumnType("datetime2(0)");

                    b.HasKey("Id");

                    b.HasIndex("CallAgentId", "StartUtc", "EndUtc")
                        .HasDatabaseName("IX_Availabilities_CallAgent_Range");

                    b.ToTable("Availabilities", null, t =>
                        {
                            t.HasCheckConstraint("CK_Availabilities_Range", "[EndUtc] > [StartUtc]");
                        });
                });

            modelBuilder.Entity("ShiftFlow.Domain.Entities.CallAgent", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2(0)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique()
                        .HasDatabaseName("UQ_CallAgents_UserId");

                    b.ToTable("CallAgents", (string)null);
                });

            modelBuilder.Entity("ShiftFlow.Domain.Entities.CallAgentProject", b =>
                {
                    b.Property<int>("CallAgentId")
                        .HasColumnType("int");

                    b.Property<int>("ProjectId")
                        .HasColumnType("int");

                    b.Property<DateTime>("AssignedAtUtc")
                        .HasColumnType("datetime2(0)");

                    b.HasKey("CallAgentId", "ProjectId");

                    b.HasIndex("ProjectId")
                        .HasDatabaseName("IX_CallAgentProjects_ProjectId");

                    b.ToTable("CallAgentProjects", (string)null);
                });

            modelBuilder.Entity("ShiftFlow.Domain.Entities.Project", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2(0)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<int>("SupervisorId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("SupervisorId", "Name")
                        .IsUnique()
                        .HasDatabaseName("UQ_Projects_Supervisor_Name");

                    b.ToTable("Projects", (string)null);
                });

            modelBuilder.Entity("ShiftFlow.Domain.Entities.Rating", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CallAgentId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2(0)");

                    b.Property<string>("Period")
                        .IsRequired()
                        .HasMaxLength(7)
                        .HasColumnType("char(7)")
                        .IsFixedLength();

                    b.Property<decimal>("Score")
                        .HasColumnType("decimal(2,1)");

                    b.HasKey("Id");

                    b.HasIndex("CallAgentId", "Period")
                        .IsUnique()
                        .HasDatabaseName("UQ_Ratings_CallAgent_Period");

                    b.ToTable("Ratings", null, t =>
                        {
                            t.HasCheckConstraint("CK_Ratings_Score", "[Score] BETWEEN 1.0 AND 5.0");
                        });
                });

            modelBuilder.Entity("ShiftFlow.Domain.Entities.Recommendation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CallAgentId")
                        .HasColumnType("int");

                    b.Property<DateTime>("ComputedAtUtc")
                        .HasColumnType("datetime2(0)");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<decimal>("Score")
                        .HasColumnType("decimal(5,2)");

                    b.Property<int>("ShiftId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CallAgentId");

                    b.HasIndex("ShiftId", "CallAgentId")
                        .IsUnique()
                        .HasDatabaseName("UQ_Recommendations_Shift_CallAgent");

                    b.HasIndex("ShiftId", "Score")
                        .IsDescending(false, true)
                        .HasDatabaseName("IX_Recommendations_Shift_Score");

                    b.ToTable("Recommendations", null, t =>
                        {
                            t.HasCheckConstraint("CK_Recommendations_Score", "[Score] BETWEEN 0 AND 100");
                        });
                });

            modelBuilder.Entity("ShiftFlow.Domain.Entities.Shift", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("AssignedCallAgentId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2(0)");

                    b.Property<DateTime>("EndUtc")
                        .HasColumnType("datetime2(0)");

                    b.Property<int>("ProjectId")
                        .HasColumnType("int");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<DateTime>("StartUtc")
                        .HasColumnType("datetime2(0)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(16)
                        .HasColumnType("nvarchar(16)")
                        .HasDefaultValue("Open");

                    b.HasKey("Id");

                    b.HasIndex("AssignedCallAgentId")
                        .HasDatabaseName("IX_Shifts_AssignedCallAgentId")
                        .HasFilter("[AssignedCallAgentId] IS NOT NULL");

                    b.HasIndex("ProjectId", "Status")
                        .HasDatabaseName("IX_Shifts_ProjectId_Status");

                    b.HasIndex("Status", "StartUtc")
                        .HasDatabaseName("IX_Shifts_Status_StartUtc");

                    b.ToTable("Shifts", null, t =>
                        {
                            t.HasCheckConstraint("CK_Shifts_Range", "[EndUtc] > [StartUtc]");

                            t.HasCheckConstraint("CK_Shifts_Status", "[Status] IN ('Open', 'Assigned', 'Released', 'Closed')");
                        });
                });

            modelBuilder.Entity("ShiftFlow.Domain.Entities.ShiftApplication", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("AppliedAtUtc")
                        .HasColumnType("datetime2(0)");

                    b.Property<int>("CallAgentId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("DecidedAtUtc")
                        .HasColumnType("datetime2(0)");

                    b.Property<int?>("DecidedByUserId")
                        .HasColumnType("int");

                    b.Property<string>("DecisionNote")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<int>("ShiftId")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("nvarchar(16)");

                    b.HasKey("Id");

                    b.HasIndex("DecidedByUserId");

                    b.HasIndex("ShiftId")
                        .IsUnique()
                        .HasDatabaseName("UX_ShiftApplications_OneApproved")
                        .HasFilter("[Status] = 'Approved'");

                    b.HasIndex("CallAgentId", "Status")
                        .HasDatabaseName("IX_ShiftApplications_CallAgent_Status");

                    SqlServerIndexBuilderExtensions.IncludeProperties(b.HasIndex("CallAgentId", "Status"), new[] { "ShiftId" });

                    b.HasIndex("ShiftId", "CallAgentId")
                        .IsUnique()
                        .HasDatabaseName("UQ_ShiftApplications_Shift_CallAgent");

                    b.HasIndex("ShiftId", "Status")
                        .HasDatabaseName("IX_ShiftApplications_Shift_Status");

                    b.ToTable("ShiftApplications", null, t =>
                        {
                            t.HasCheckConstraint("CK_ShiftApplications_Status", "[Status] IN ('Pending', 'Approved', 'Rejected')");
                        });
                });

            modelBuilder.Entity("ShiftFlow.Domain.Entities.Supervisor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2(0)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique()
                        .HasDatabaseName("UQ_Supervisors_UserId");

                    b.ToTable("Supervisors", (string)null);
                });

            modelBuilder.Entity("ShiftFlow.Domain.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2(0)")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("nvarchar(16)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.HasKey("Id");

                    b.HasIndex("Username")
                        .IsUnique()
                        .HasDatabaseName("UQ_Users_Username");

                    b.ToTable("Users", null, t =>
                        {
                            t.HasCheckConstraint("CK_Users_Role", "[Role] IN ('Manager', 'Supervisor', 'CallAgent')");
                        });
                });

            modelBuilder.Entity("ShiftFlow.Domain.Entities.AttendanceSession", b =>
                {
                    b.HasOne("ShiftFlow.Domain.Entities.CallAgent", "CallAgent")
                        .WithMany("AttendanceSessions")
                        .HasForeignKey("CallAgentId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("ShiftFlow.Domain.Entities.Shift", "Shift")
                        .WithMany("AttendanceSessions")
                        .HasForeignKey("ShiftId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("CallAgent");

                    b.Navigation("Shift");
                });

            modelBuilder.Entity("ShiftFlow.Domain.Entities.Availability", b =>
                {
                    b.HasOne("ShiftFlow.Domain.Entities.CallAgent", "CallAgent")
                        .WithMany("Availabilities")
                        .HasForeignKey("CallAgentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CallAgent");
                });

            modelBuilder.Entity("ShiftFlow.Domain.Entities.CallAgent", b =>
                {
                    b.HasOne("ShiftFlow.Domain.Entities.User", "User")
                        .WithOne("CallAgent")
                        .HasForeignKey("ShiftFlow.Domain.Entities.CallAgent", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("ShiftFlow.Domain.Entities.CallAgentProject", b =>
                {
                    b.HasOne("ShiftFlow.Domain.Entities.CallAgent", "CallAgent")
                        .WithMany("CallAgentProjects")
                        .HasForeignKey("CallAgentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ShiftFlow.Domain.Entities.Project", "Project")
                        .WithMany("CallAgentProjects")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("CallAgent");

                    b.Navigation("Project");
                });

            modelBuilder.Entity("ShiftFlow.Domain.Entities.Project", b =>
                {
                    b.HasOne("ShiftFlow.Domain.Entities.Supervisor", "Supervisor")
                        .WithMany("Projects")
                        .HasForeignKey("SupervisorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Supervisor");
                });

            modelBuilder.Entity("ShiftFlow.Domain.Entities.Rating", b =>
                {
                    b.HasOne("ShiftFlow.Domain.Entities.CallAgent", "CallAgent")
                        .WithMany("Ratings")
                        .HasForeignKey("CallAgentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CallAgent");
                });

            modelBuilder.Entity("ShiftFlow.Domain.Entities.Recommendation", b =>
                {
                    b.HasOne("ShiftFlow.Domain.Entities.CallAgent", "CallAgent")
                        .WithMany("Recommendations")
                        .HasForeignKey("CallAgentId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("ShiftFlow.Domain.Entities.Shift", "Shift")
                        .WithMany("Recommendations")
                        .HasForeignKey("ShiftId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CallAgent");

                    b.Navigation("Shift");
                });

            modelBuilder.Entity("ShiftFlow.Domain.Entities.Shift", b =>
                {
                    b.HasOne("ShiftFlow.Domain.Entities.CallAgent", "AssignedCallAgent")
                        .WithMany("AssignedShifts")
                        .HasForeignKey("AssignedCallAgentId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("ShiftFlow.Domain.Entities.Project", "Project")
                        .WithMany("Shifts")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AssignedCallAgent");

                    b.Navigation("Project");
                });

            modelBuilder.Entity("ShiftFlow.Domain.Entities.ShiftApplication", b =>
                {
                    b.HasOne("ShiftFlow.Domain.Entities.CallAgent", "CallAgent")
                        .WithMany("ShiftApplications")
                        .HasForeignKey("CallAgentId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("ShiftFlow.Domain.Entities.User", "DecidedByUser")
                        .WithMany("DecidedApplications")
                        .HasForeignKey("DecidedByUserId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("ShiftFlow.Domain.Entities.Shift", "Shift")
                        .WithMany("ShiftApplications")
                        .HasForeignKey("ShiftId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CallAgent");

                    b.Navigation("DecidedByUser");

                    b.Navigation("Shift");
                });

            modelBuilder.Entity("ShiftFlow.Domain.Entities.Supervisor", b =>
                {
                    b.HasOne("ShiftFlow.Domain.Entities.User", "User")
                        .WithOne("Supervisor")
                        .HasForeignKey("ShiftFlow.Domain.Entities.Supervisor", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("ShiftFlow.Domain.Entities.CallAgent", b =>
                {
                    b.Navigation("AssignedShifts");

                    b.Navigation("AttendanceSessions");

                    b.Navigation("Availabilities");

                    b.Navigation("CallAgentProjects");

                    b.Navigation("Ratings");

                    b.Navigation("Recommendations");

                    b.Navigation("ShiftApplications");
                });

            modelBuilder.Entity("ShiftFlow.Domain.Entities.Project", b =>
                {
                    b.Navigation("CallAgentProjects");

                    b.Navigation("Shifts");
                });

            modelBuilder.Entity("ShiftFlow.Domain.Entities.Shift", b =>
                {
                    b.Navigation("AttendanceSessions");

                    b.Navigation("Recommendations");

                    b.Navigation("ShiftApplications");
                });

            modelBuilder.Entity("ShiftFlow.Domain.Entities.Supervisor", b =>
                {
                    b.Navigation("Projects");
                });

            modelBuilder.Entity("ShiftFlow.Domain.Entities.User", b =>
                {
                    b.Navigation("CallAgent");

                    b.Navigation("DecidedApplications");

                    b.Navigation("Supervisor");
                });
#pragma warning restore 612, 618
        }
    }
}
