// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ShiftFlow.Infrastructure.Persistence;

#nullable disable

namespace ShiftFlow.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ShiftFlow.Domain.Entities.Availability", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2(0)");

                    b.Property<DateTime>("EndUtc")
                        .HasColumnType("datetime2(0)");

                    b.Property<int>("ExpertId")
                        .HasColumnType("int");

                    b.Property<DateTime>("StartUtc")
                        .HasColumnType("datetime2(0)");

                    b.HasKey("Id");

                    b.HasIndex("ExpertId", "StartUtc", "EndUtc")
                        .HasDatabaseName("IX_Availabilities_Expert_Range");

                    b.ToTable("Availabilities", null, t =>
                        {
                            t.HasCheckConstraint("CK_Availabilities_Range", "[EndUtc] > [StartUtc]");
                        });
                });

            modelBuilder.Entity("ShiftFlow.Domain.Entities.Employer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2(0)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique()
                        .HasDatabaseName("UQ_Employers_UserId");

                    b.ToTable("Employers", (string)null);
                });

            modelBuilder.Entity("ShiftFlow.Domain.Entities.Expert", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2(0)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique()
                        .HasDatabaseName("UQ_Experts_UserId");

                    b.ToTable("Experts", (string)null);
                });

            modelBuilder.Entity("ShiftFlow.Domain.Entities.ExpertProject", b =>
                {
                    b.Property<int>("ExpertId")
                        .HasColumnType("int");

                    b.Property<int>("ProjectId")
                        .HasColumnType("int");

                    b.Property<DateTime>("AssignedAtUtc")
                        .HasColumnType("datetime2(0)");

                    b.HasKey("ExpertId", "ProjectId");

                    b.HasIndex("ProjectId")
                        .HasDatabaseName("IX_ExpertProjects_ProjectId");

                    b.ToTable("ExpertProjects", (string)null);
                });

            modelBuilder.Entity("ShiftFlow.Domain.Entities.ExpertRating", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2(0)");

                    b.Property<int>("ExpertId")
                        .HasColumnType("int");

                    b.Property<string>("Period")
                        .IsRequired()
                        .HasMaxLength(7)
                        .HasColumnType("char(7)")
                        .IsFixedLength();

                    b.Property<decimal>("Score")
                        .HasColumnType("decimal(2,1)");

                    b.HasKey("Id");

                    b.HasIndex("ExpertId", "Period")
                        .IsUnique()
                        .HasDatabaseName("UQ_ExpertRatings_Expert_Period");

                    b.ToTable("ExpertRatings", null, t =>
                        {
                            t.HasCheckConstraint("CK_ExpertRatings_Score", "[Score] BETWEEN 1.0 AND 5.0");
                        });
                });

            modelBuilder.Entity("ShiftFlow.Domain.Entities.Project", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2(0)");

                    b.Property<int>("EmployerId")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.HasKey("Id");

                    b.HasIndex("EmployerId", "Name")
                        .IsUnique()
                        .HasDatabaseName("UQ_Projects_Employer_Name");

                    b.ToTable("Projects", (string)null);
                });

            modelBuilder.Entity("ShiftFlow.Domain.Entities.Recommendation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("ComputedAtUtc")
                        .HasColumnType("datetime2(0)");

                    b.Property<int>("ExpertId")
                        .HasColumnType("int");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<decimal>("Score")
                        .HasColumnType("decimal(5,2)");

                    b.Property<int>("ShiftId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ExpertId");

                    b.HasIndex("ShiftId", "ExpertId")
                        .IsUnique()
                        .HasDatabaseName("UQ_Recommendations_Shift_Expert");

                    b.HasIndex("ShiftId", "Score")
                        .IsDescending(false, true)
                        .HasDatabaseName("IX_Recommendations_Shift_Score");

                    b.ToTable("Recommendations", null, t =>
                        {
                            t.HasCheckConstraint("CK_Recommendations_Score", "[Score] BETWEEN 0 AND 100");
                        });
                });

            modelBuilder.Entity("ShiftFlow.Domain.Entities.Shift", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2(0)");

                    b.Property<DateTime>("EndUtc")
                        .HasColumnType("datetime2(0)");

                    b.Property<int>("ProjectId")
                        .HasColumnType("int");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<DateTime>("StartUtc")
                        .HasColumnType("datetime2(0)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(16)
                        .HasColumnType("nvarchar(16)")
                        .HasDefaultValue("Open");

                    b.HasKey("Id");

                    b.HasIndex("ProjectId", "Status")
                        .HasDatabaseName("IX_Shifts_ProjectId_Status");

                    b.HasIndex("Status", "StartUtc")
                        .HasDatabaseName("IX_Shifts_Status_StartUtc");

                    b.ToTable("Shifts", null, t =>
                        {
                            t.HasCheckConstraint("CK_Shifts_Range", "[EndUtc] > [StartUtc]");

                            t.HasCheckConstraint("CK_Shifts_Status", "[Status] IN ('Open', 'Closed')");
                        });
                });

            modelBuilder.Entity("ShiftFlow.Domain.Entities.ShiftApplication", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("AppliedAtUtc")
                        .HasColumnType("datetime2(0)");

                    b.Property<DateTime?>("DecidedAtUtc")
                        .HasColumnType("datetime2(0)");

                    b.Property<int?>("DecidedByUserId")
                        .HasColumnType("int");

                    b.Property<string>("DecisionNote")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<int>("ExpertId")
                        .HasColumnType("int");

                    b.Property<int>("ShiftId")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("nvarchar(16)");

                    b.HasKey("Id");

                    b.HasIndex("DecidedByUserId");

                    b.HasIndex("ShiftId")
                        .IsUnique()
                        .HasDatabaseName("UX_ShiftApplications_OneApproved")
                        .HasFilter("[Status] = 'Approved'");

                    b.HasIndex("ExpertId", "Status")
                        .HasDatabaseName("IX_ShiftApplications_Expert_Status");

                    SqlServerIndexBuilderExtensions.IncludeProperties(b.HasIndex("ExpertId", "Status"), new[] { "ShiftId" });

                    b.HasIndex("ShiftId", "ExpertId")
                        .IsUnique()
                        .HasDatabaseName("UQ_ShiftApplications_Shift_Expert");

                    b.HasIndex("ShiftId", "Status")
                        .HasDatabaseName("IX_ShiftApplications_Shift_Status");

                    b.ToTable("ShiftApplications", null, t =>
                        {
                            t.HasCheckConstraint("CK_ShiftApplications_Status", "[Status] IN ('Pending', 'Approved', 'Rejected')");
                        });
                });

            modelBuilder.Entity("ShiftFlow.Domain.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2(0)")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("nvarchar(16)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.HasKey("Id");

                    b.HasIndex("Username")
                        .IsUnique()
                        .HasDatabaseName("UQ_Users_Username");

                    b.ToTable("Users", null, t =>
                        {
                            t.HasCheckConstraint("CK_Users_Role", "[Role] IN ('Employer', 'Expert')");
                        });
                });

            modelBuilder.Entity("ShiftFlow.Domain.Entities.Availability", b =>
                {
                    b.HasOne("ShiftFlow.Domain.Entities.Expert", "Expert")
                        .WithMany("Availabilities")
                        .HasForeignKey("ExpertId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Expert");
                });

            modelBuilder.Entity("ShiftFlow.Domain.Entities.Employer", b =>
                {
                    b.HasOne("ShiftFlow.Domain.Entities.User", "User")
                        .WithOne("Employer")
                        .HasForeignKey("ShiftFlow.Domain.Entities.Employer", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("ShiftFlow.Domain.Entities.Expert", b =>
                {
                    b.HasOne("ShiftFlow.Domain.Entities.User", "User")
                        .WithOne("Expert")
                        .HasForeignKey("ShiftFlow.Domain.Entities.Expert", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("ShiftFlow.Domain.Entities.ExpertProject", b =>
                {
                    b.HasOne("ShiftFlow.Domain.Entities.Expert", "Expert")
                        .WithMany("ExpertProjects")
                        .HasForeignKey("ExpertId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ShiftFlow.Domain.Entities.Project", "Project")
                        .WithMany("ExpertProjects")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Expert");

                    b.Navigation("Project");
                });

            modelBuilder.Entity("ShiftFlow.Domain.Entities.ExpertRating", b =>
                {
                    b.HasOne("ShiftFlow.Domain.Entities.Expert", "Expert")
                        .WithMany("ExpertRatings")
                        .HasForeignKey("ExpertId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Expert");
                });

            modelBuilder.Entity("ShiftFlow.Domain.Entities.Project", b =>
                {
                    b.HasOne("ShiftFlow.Domain.Entities.Employer", "Employer")
                        .WithMany("Projects")
                        .HasForeignKey("EmployerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Employer");
                });

            modelBuilder.Entity("ShiftFlow.Domain.Entities.Recommendation", b =>
                {
                    b.HasOne("ShiftFlow.Domain.Entities.Expert", "Expert")
                        .WithMany("Recommendations")
                        .HasForeignKey("ExpertId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("ShiftFlow.Domain.Entities.Shift", "Shift")
                        .WithMany("Recommendations")
                        .HasForeignKey("ShiftId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Expert");

                    b.Navigation("Shift");
                });

            modelBuilder.Entity("ShiftFlow.Domain.Entities.Shift", b =>
                {
                    b.HasOne("ShiftFlow.Domain.Entities.Project", "Project")
                        .WithMany("Shifts")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Project");
                });

            modelBuilder.Entity("ShiftFlow.Domain.Entities.ShiftApplication", b =>
                {
                    b.HasOne("ShiftFlow.Domain.Entities.User", "DecidedByUser")
                        .WithMany("DecidedApplications")
                        .HasForeignKey("DecidedByUserId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("ShiftFlow.Domain.Entities.Expert", "Expert")
                        .WithMany("ShiftApplications")
                        .HasForeignKey("ExpertId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("ShiftFlow.Domain.Entities.Shift", "Shift")
                        .WithMany("ShiftApplications")
                        .HasForeignKey("ShiftId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DecidedByUser");

                    b.Navigation("Expert");

                    b.Navigation("Shift");
                });

            modelBuilder.Entity("ShiftFlow.Domain.Entities.Employer", b =>
                {
                    b.Navigation("Projects");
                });

            modelBuilder.Entity("ShiftFlow.Domain.Entities.Expert", b =>
                {
                    b.Navigation("Availabilities");

                    b.Navigation("ExpertProjects");

                    b.Navigation("ExpertRatings");

                    b.Navigation("Recommendations");

                    b.Navigation("ShiftApplications");
                });

            modelBuilder.Entity("ShiftFlow.Domain.Entities.Project", b =>
                {
                    b.Navigation("ExpertProjects");

                    b.Navigation("Shifts");
                });

            modelBuilder.Entity("ShiftFlow.Domain.Entities.Shift", b =>
                {
                    b.Navigation("Recommendations");

                    b.Navigation("ShiftApplications");
                });

            modelBuilder.Entity("ShiftFlow.Domain.Entities.User", b =>
                {
                    b.Navigation("DecidedApplications");

                    b.Navigation("Employer");

                    b.Navigation("Expert");
                });
#pragma warning restore 612, 618
        }
    }
}
